# Generated by Django 5.1.15 on 2026-09-26 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado')], default='AGENDADO', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='clientes.cliente')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='servicos.servico')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-data', '-horario'],
                'constraints': [models.UniqueConstraint(fields=('data', 'horario'), name='unique_agendamento_data_horario')],
            },
        ),
    ]
